
package org.gaurav.testmartwebservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ProductCatalog", targetNamespace = "http://TestmartWebService.gaurav.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProductCatalog {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<org.gaurav.testmartwebservice.Product>
     */
    @WebMethod
    @WebResult(name = "Product", targetNamespace = "")
    @RequestWrapper(localName = "getProductCategory", targetNamespace = "http://TestmartWebService.gaurav.org/", className = "org.gaurav.testmartwebservice.GetProductCategory")
    @ResponseWrapper(localName = "getProductCategoryResponse", targetNamespace = "http://TestmartWebService.gaurav.org/", className = "org.gaurav.testmartwebservice.GetProductCategoryResponse")
    public List<Product> getProductCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addProduct", targetNamespace = "http://TestmartWebService.gaurav.org/", className = "org.gaurav.testmartwebservice.AddProduct")
    @ResponseWrapper(localName = "addProductResponse", targetNamespace = "http://TestmartWebService.gaurav.org/", className = "org.gaurav.testmartwebservice.AddProductResponse")
    public boolean addProduct(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCategory", targetNamespace = "http://TestmartWebService.gaurav.org/", className = "org.gaurav.testmartwebservice.AddCategory")
    @ResponseWrapper(localName = "addCategoryResponse", targetNamespace = "http://TestmartWebService.gaurav.org/", className = "org.gaurav.testmartwebservice.AddCategoryResponse")
    public boolean addCategory(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
