
package org.gaurav.testmartwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ProductCatalogService", targetNamespace = "http://TestmartWebService.gaurav.org/", wsdlLocation = "http://localhost:7001/TestMart/ProductCatalogService?WSDL")
public class ProductCatalogService
    extends Service
{

    private final static URL PRODUCTCATALOGSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(org.gaurav.testmartwebservice.ProductCatalogService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = org.gaurav.testmartwebservice.ProductCatalogService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:7001/TestMart/ProductCatalogService?WSDL");
            System.out.print("WSDL");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:7001/TestMart/ProductCatalogService?WSDL', retrying as a local file");
            logger.warning(e.getMessage());
            System.out.print("Failed to create URL for the wsdl Location: 'http://localhost:7001/TestMart/ProductCatalogService?WSDL', retrying as a local file");
        }
        PRODUCTCATALOGSERVICE_WSDL_LOCATION = url;
    }

    public ProductCatalogService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductCatalogService() {
        super(PRODUCTCATALOGSERVICE_WSDL_LOCATION, new QName("http://TestmartWebService.gaurav.org/", "ProductCatalogService"));
    }

    /**
     * 
     * @return
     *     returns ProductCatalog
     */
    @WebEndpoint(name = "ProductCatalogPort")
    public ProductCatalog getProductCatalogPort() {
        return super.getPort(new QName("http://TestmartWebService.gaurav.org/", "ProductCatalogPort"), ProductCatalog.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductCatalog
     */
    @WebEndpoint(name = "ProductCatalogPort")
    public ProductCatalog getProductCatalogPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://TestmartWebService.gaurav.org/", "ProductCatalogPort"), ProductCatalog.class, features);
    }

}
